### ISSUE TITLE
Feature Request: Is this repository still maintained?

### ISSUE THREAD

**Issue by Peter-Roh** [omidnikrah/profile-activity-generator#3]
I think it would be helpful if there's a button to click all the squares at once so that I can try to make the tone one step up.
Of course, the tone must be able to go down once you reach the highest.

**Comment by omidnikrah** [comment]
@Peter-Roh Hi Peter,
That's a great idea, If I find a free time I can implement it, and also if you can implement it, pull request welcome :)

**Comment by Peter-Roh** [comment]
Thx! Working on it!
